
import os
import gradio as gr
from dotenv import load_dotenv
import sys
sys.path.append("../src")
from assistant import Assistant

load_dotenv()

UI_PORT: int = int(os.getenv("UI_PORT", "8046"))


FAISS_INDEX_PATH = "../app/scenario/faiss_index"
PDF_PATH = "../app/scenario/How-Women-Rise.pdf"

qa_assistant = Assistant(pdf_path=PDF_PATH, index_path=FAISS_INDEX_PATH)
def respond(question, history):
    """
    Get the response for a given question using the QA assistant.

    Args:
        question (str): The question to be asked.
        history (list): The list of previous questions and answers.

    Returns:
        str: The response generated by the QA assistant.
    """
    response = qa_assistant.request(question)
    return response


PLACE_HOLDER = "¡Hola!, ¿En que te puedo ayudar?"
BOTH_ICON = "assets/bot.png"
USER_ICON = "assets/user.png"
chatbot = gr.ChatInterface(
    fn=respond,
    chatbot=gr.Chatbot(elem_id="chatbot", height="auto", avatar_images=[USER_ICON, BOTH_ICON]),
    title="",
    textbox=gr.Textbox(placeholder=PLACE_HOLDER, container=False, scale=7),
    clear_btn="Limpiar",
    retry_btn=None,
    undo_btn=None,
    submit_btn="Enviar",
    theme=gr.themes.Default(primary_hue="purple", secondary_hue="indigo"),
)

if __name__ == "__main__":
    chatbot.launch(server_name="0.0.0.0", server_port=UI_PORT)
